project:
  type: website
  output-dir: docs
    
website:
  title: "Zackary Wais Website"
navbar:
  left:
    - text: "Home"
      href: index.qmd
    - text: "Bio"
      href: Bio.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
