---
title: "Zackary Wais Bio"
---

Hello! My name is Zackary Wais, and I am currently pursuing a Bachelor of Science with a major in Mathematics and minors in Statistics and French, alongside the business fundamentals certificate at the University of Toronto. My academic journey is deeply intertwined with my passion for analyzing patterns, solving complex problems, and utilizing statistical methods to make informed decisions. This passion extends beyond the classroom into my professional experiences.

My career began with a introduction to the search fund model from the Stanford GSB, ultimately leading me to intern at Baton in New York as a Finance Intern and at Huntstone Capital in Toronto as a Private Equity Senior Analyst, among other roles. These experiences allowed me to implement dynamic financial models, conduct comprehensive analyses, and leverage CRM software to evaluate investment opportunities and enhance investor presentations.

Beyond my academic and professional life, I have been involved in extracurricular activities at the University of Toronto, serving as the Director of Corporate Relations for the University of Toronto Sports Business club and as a Business Development Associate for the University of Toronto Consulting Association. These roles have honed my leadership and strategic planning skills, as I've secured partnerships, managed databases, and organized events to foster industry relationships.

As I continue to navigate my academic and professional journey, I am eager to apply my statistical knowledge and analytical skills to new experiences both in and outside of the classroom!
